[package]
name = "image-effects"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.109"  # Updated version
base64 = "0.22.1"
image = "0.25.8"

[dependencies.web-sys]
version = "0.3.69"
features = [
    "console",
]